app_key: "w1qn8qata3ibvff"
app_secret: "etqox1b236nddx9"
access_token: "sl.BGVRdT3wXVmfFYz4EqC7VFFZ2qTUc_F1qaFCgIFNjByE-YSCPWR3D0jeDT3R454xjB9PRTeHdWumZdmfn3It59lBQmUAqVKm0dJ9MUNE70XYP3vehAV4vQWkGvmTmdQVWU6x6kw"
access_token_secret: "..."
user_id: "..."
access_type: "dropbox"